(lang dune 3.16)

(name Assignment1)

(generate_opam_files true)

(source
 (github ChristianBP/Grad-School-Work))

(authors "Christian Parker")

(maintainers "Christian Parker")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name Assignment1)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune alcotest)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
